In [1]:
from scipy import stats

In [3]:
stats.uniform(7,15-7).cdf(9.5)-stats.uniform(7,15-7).cdf(8.2)

0.1625000000000001

In [5]:
c = (11-6)/(15-6)
scale = 15-6
stats.triang(c,6,scale).cdf(14) - stats.triang(c,6,scale).cdf(8) 

0.8833333333333332

In [7]:
stats.norm(13,2.3).cdf(15)-stats.norm(13,2.3).cdf(9.8)

0.725664395523142

In [12]:
stats.norm(13,2.3).ppf(0.025)

8.492082835557875

In [14]:
#Conduct a t-test to see if the mean of this data is above 27. Use  α=.05 .
# 31,24,27,27,31,26,30,31

import pandas as pd
sample = pd.Series([31,24,27,27,31,26,30,31])

In [15]:
sample.mean()

28.375

In [30]:
degree_of_freedom = len(sample) - 1

z = stats.t(degree_of_freedom).ppf(0.95)
print(z)

1.894578605061305


In [27]:
#by default the ttest using 1 sample in python is always 2 tailed
z_val, pval_2_tail = stats.ttest_1samp(sample, 27)
print(stats.ttest_1samp(sample,27))

Ttest_1sampResult(statistic=1.4286230627501737, pvalue=0.19617645073072726)


In [29]:
#What is the p-value of your t-test?

pval_1_tail = pval_2_tail / 2
print(pval_1_tail)

0.09808822536536363


In [32]:
#Can you say that the mean of the data is greater than 27?
z_val > z 
#z_val is less than z therefore we can not say that 

False

In [43]:
import numpy as np
#You repeat the MoonDoe survey on 100 new customers. Your new data is below.
#               Testvalue	 	Expected Value
#Blue				32				25
#Red				27				25
#Green				18				25
#Yellow				23				25

testval = np.array([32,27,18,23])
expval = np.array([25,25,25,25])

#Run the chi-square test. What is the p-value of your ChiSq Test?
test_stat, pval = stats.chisquare(testval,expval)
print(stats.chisquare(testval,expval))

Power_divergenceResult(statistic=4.24, pvalue=0.23668751492438694)


In [45]:
#Using  α=.05  can you say that your customers are significantly different than the expected distribution?
df = len(testval) - 1
critical_val = stats.chi2.ppf(0.95,df)
print(critical_val)

7.814727903251179


In [46]:
rating = pd.Series([0.0404,0.0445,0.0429,0.0449,0.0434,0.0438,0.0402,0.0407,0.0448,0.041])

In [112]:
dof = len(rating) - 1
loc = rating.mean()
#because it is a t distribution the numerator in a z value formula must be divided with the square root of the no. of. observation
scale = rating.std() / np.sqrt(len(rating))
dist = stats.t(dof, loc, scale)

In [114]:
dist.ppf(0.975)

0.04402239551103818

In [115]:
dist.ppf(0.025)

0.04129760448896181

In [116]:
rating_stat, rating_pval2tail = stats.ttest_1samp(rating, 0.043)

In [120]:
rating_pval1tail = rating_pval2tail / 2
print(1-rating_pval1tail)

0.7069119454465335


In [100]:
stats.t(dof).ppf(0.95)

1.8331129326536335

In [118]:
rating_stat

-0.5645448983796457

In [131]:
#Lily ambulance service, which is based in Boston, attends to emergency medical calls in the city. 
#They have a 24-hour call center which receives all calls, takes notes about location and patient’s 
#status and assigns the nearest ambulance vehicle to the call. The ambulance vehicle gets a call 
#notifying them of the same. They dispatch to the location after receiving the call and help the 
#patient. The wait time, which is the average time from when the call is received to when the ambulance 
#arrives at the scene, is 17.5 minutes.

#Lily Ambulance Services realized that technology intervention may reduce their operating cost and 
#hence introduced an app where people can request for an ambulance using an app (by putting in some 
#of the important information like location and patient condition). Ambulance vehicles directly receive 
#a notification, reducing the need for a call center. Lily Ambulance Services decided to keep the call 
#center while testing the app functionality.

#You have been hired to evaluate if the app had any impact on service.

#By studying a sample of the data with 150 app requested ambulances, it was determined that the wait 
#times have a mean of 16 minutes with a standard deviation of 6 minutes.

#You decide to conduct a hypothesis test to evaluate if the wait times using the app based requests 
#are equal to that of the regular call based requests. You assume a significance level of 5%:

#H0 : Average wait times in app requests are equal to call based requests.

#H1 : Average wait times in app requests are not equal to call based requests.

#What is the corresponding critical value (the z-value) of the app based requests?
stats.norm(0,1).ppf(0.975) 

1.959963984540054

In [139]:
#What is the upper limit of this confidence interval?

loc = 16
#in scale we use stddev / squareroot of observation because this is a sample on n observations
scale = 6 / np.sqrt(150)
stats.norm(loc,scale).ppf(0.975)


16.96018233527106

In [140]:
#What is the lower limit of this confidence interval?
stats.norm(loc,scale).ppf(0.025)

15.039817664728938

In [144]:
#You have already calculated the confidence interval for the mean at a 95% confidence level in part 3. 
#Your H0 states that population mean and sample mean are equal. To see if you can reject this null 
#hypothesis all is left to do is check, if the population mean is within this confidence interval 
#of the sample mean. If the population mean is within the confidence interval you cannot reject H0. 
#In this case, because the population mean (17.5) is outside the confidence interval of (15.04, 16.96)

17.5 > 16.96

True

In [145]:
#You sell 5 types of TVs at your electronics store. Your store is a small part of a larger chain. 
#Over the past few months, corporate has developed a distribution of customer preferences for these 
#TV types. You decided to interview 185 local customers because you don't think that corporate 
#expectations will hold at your particular store. Conduct a Chi-Square test to see if your customers 
#are in a different distribution than the one corporate expects them to be in. 
#Your survey results and expected values are below.

           #Testvalue	Expected Value
#Product1		18			  28
#Product2		39			  47
#Product3		56			  48
#Product4		38			  35
#Product5		34			  27

In [146]:
testval = pd.Series([18,39,56,38,34])
expval = pd.Series([28,47,48,35,27])

In [147]:
#What is the p-value of your ChiSq Test?
test_stat, pval = stats.chisquare(testval,expval)
print(stats.chisquare(testval,expval))

Power_divergenceResult(statistic=8.33842170437915, pvalue=0.0799390495646549)


In [148]:
#Using  α=.05  can you say that your customers are significantly different from corporate's expected distribution?

dof = len(expval)-1
crit_stat = stats.chi2.ppf(0.95,dof)
print(crit_stat)
#Since your p value is greater than your alpha value of .05, and hence correspondingly test_stat < critical stat
#you can not say that the distributions are significantly different.

9.487729036781154

In [149]:
#You were recently promoted to assist the general manager Donette at a distribution center 
#of ‘High Quality Pharmaceutical Imports’ in Nairobi. 
#You received the promotion because she was convinced that your experience in rigorous 
#quantitative analyses will focus efforts to improve warehouse performance and help make better decisions.

#Several initiatives to improve warehouse operations were started before you joined the team. 
#One of these initiatives focused on selecting well-performing suppliers through a new supplier 
#evaluation and selection method. Among different attributes that were considered in the evaluation 
#and selection of suppliers, on-time delivery was very important because many different warehouse 
#processes depend on suppliers delivering on-time.

#Your colleagues, Isela and Robbie, have tracked the delivery of all SKUs over the last 12 months 
#and calculated the positive or negative difference (in days) from the promised delivery date.

#In your last discussion, Donette said that she would like to know the 90% prediction interval for 
#the time difference between promised delivery date and the actual delivery for the next delivery. 
#Accordingly, you want to create a 90% prediction interval based on the given sample distribution.

#To create an example for Donette you pick SKU A103. This SKU has a mean time differences of 16.25 days 
#and a standard deviation of 8.83 days from a sample of 136 past deliveries. You assume that the time 
#differences are normally distributed.

'C:\\Users\\LENOVO\\MITx SC0 Supply Chain Analytics\\Module3_statistics'

In [152]:
#Calculate the lower boundary for a 90% confidence interval.
#Calculate the upper boundary for a 90% confidence interval.
#Calculate the lower boundary for a 90% prediction interval.
#Calculate the upper boundary for a 90% prediction interval.

#confidence interval pertains to our sample, hence the square root of the observations
#prediction interval assumes the population mean based on the sample, hence the absence square root of the observations
print('lower 90% confidence interval: ',stats.norm(16.25,8.83/np.sqrt(136)).ppf(0.05))
print('upper 90% confidence interval: ',stats.norm(16.25,8.83/np.sqrt(136)).ppf(0.95))
print('upper 90% prediction interval: ',stats.norm(16.25,8.83).ppf(0.05))
print('upper 90% prediction interval: ',stats.norm(16.25,8.83).ppf(0.95))

lower 90% confidence interval:  15.004572341882882
upper 90% confidence interval:  17.495427658117116
upper 90% prediction interval:  1.7259424740184954
upper 90% prediction interval:  30.774057525981497


In [197]:
#You pick SKU B381 to create an example for your colleagues. 
#For this SKU you find a sample of 138 past deliveries. The average time difference 
#between promised delivery date and actual delivery in this sample is 21.38 days 
#with a standard deviation of 10.56 of days. You assume that the time differences are normally distributed. 
#Before the new methods were introduced the average time difference was 20.31 days.

#H0:  The average time difference after introducing the new methods is the same as 
#    the average time difference before introducing the new methods.

#H1: The average time difference after introducing the new methods is not the same 
#    as the average difference before introducing the new methods.

#Calculate the p-value.
#1st method
stats.norm(21.38, 10.56/np.sqrt(138)).cdf(20.31) * 2 #multiplied by two because this is a two tailed test

#2nd method
#c = (21.38 - 20.31)*np.sqrt(138)/10.56
#(1 - stats.norm().cdf(c))*2

#since p value / 2 is greater than the lower alpha of 0.025 for 95% confidence interval, then we can't reject H0 

0.23392530353559293

In [173]:
#In the dicussion with Donette, Isela, and Robbie you notice that calculating positive and negative time differences 
#and averaging them may skew the performance evaluation. You are mainly interested in understanding if you have more 
#delays than before introducing the new supplier evaluation and selection methods.

#You pick SKU C938 to create an example for your colleagues. The table below gives all the positive time differences, 
#i.e. delays, from the announced lead time since the new method was introduced:

#You assume that you can use a t-distribution.

#In the past the average positive time difference for SKU C938 was 6.16 days. You formulate the following hypothesis test:

#H0:  The average positive time difference after introducing the new methods is not higher 
    #than the average difference before introducing the new methods.

#H1:  The average positive time difference after introducing the new methods is higher 
    #than the average difference before introducing the new methods.

delivery = pd.DataFrame({'Deliveries#': [1,2,3,4,5,6,7,8,9,10,11,12],'Timediff':[11,14,9,7,5,9,10,1,3,15,2,1]})

In [174]:
delivery = delivery.set_index('Deliveries#')

In [175]:
delivery

Timediff
Deliveries#          
1                  11
2                  14
3                   9
4                   7
5                   5
6                   9
7                  10
8                   1
9                   3
10                 15
11                  2
12                  1

In [177]:
#Calculate the p-value!
#method 1

stat, pval2tail = stats.ttest_1samp(delivery, 6.16)

In [179]:
pval2tail/2

array([0.22781695])

In [188]:
#method 2
dof = len(delivery) - 1
loc = delivery.mean()
scale = delivery.std()/np.sqrt(len(delivery))

stats.t(dof, loc, scale).cdf(6.16)

array([0.22781695])

In [190]:
#You want to reach a 95% confidence level. Would you reject your  H0 ?

#this is a 1 tail test because the hypothesis pertains to 'higher than' a certain value
#95% confidence interval means the critical value is at 5%, corresponding to the 4.718
#since 6.16 is past the 4.718 value, then we can not reject the H0

stats.t(dof,loc,scale).ppf(0.05)

array([4.71866711])